<?php

$base_dir = dirname(__FILE__);
require_once $base_dir.'/../lib/GangliaAcl.php';

/**
 * Test class for GangliaAcl.
 * Generated by PHPUnit on 2011-04-20 at 20:35:07.
 */
class GangliaAclTest extends PHPUnit_Framework_TestCase {
  
    protected function setUp() {
        $this->object = new GangliaAcl;
    }
    
    // This is the normal way to access the ACL.
    public function testGetInstance() {
      $obj1 = GangliaAcl::getInstance();
      $obj2 = GangliaAcl::getInstance();
      
      $this->assertEquals( $obj1, $obj2 );
    }
    
    public function testGuestCanViewNormalClusters() {
      $this->assertTrue( $this->object->isAllowed( GangliaAcl::GUEST, GangliaAcl::ALL, 'view' ) );
    }
    
    public function testAdminCanViewNormalClusters() {
      $this->assertTrue( $this->object->isAllowed( GangliaAcl::ADMIN, GangliaAcl::ALL, 'view' ) );
    }
    
    public function testGuestCannotEdit() {
      $this->assertFalse( $this->object->isAllowed( GangliaAcl::GUEST, GangliaAcl::ALL, 'edit' ) );
    }
    
    public function testAdminCanEdit() {
      $this->assertTrue( $this->object->isAllowed( GangliaAcl::ADMIN, GangliaAcl::ALL, 'edit' ) );
    }
    
    public function testAdminCanAccessPrivateCluster() {
      $this->object->addPrivateCluster( 'clustername' );
      $this->assertTrue( $this->object->isAllowed( GangliaAcl::ADMIN, 'clustername', 'view' ) );
      $this->assertTrue( $this->object->isAllowed( GangliaAcl::ADMIN, 'clustername', 'edit' ) );
    }
    
    public function testGuestCannotAccessPrivateCluster() {
      $this->object->addPrivateCluster( 'clustername' );
      $this->assertFalse( $this->object->isAllowed( GangliaAcl::GUEST, 'clustername', 'view' ) );
      $this->assertFalse( $this->object->isAllowed( GangliaAcl::GUEST, 'clustername', 'edit' ) );
    }
    
    public function testUserMayBeGrantedViewAccessToPrivateCluster() {
      $this->object->addPrivateCluster( 'clustername' );
      $this->object->addRole( 'newuser', GangliaAcl::GUEST );
      $this->object->allow( 'newuser', 'clustername', 'view' );
      
      $this->assertTrue( $this->object->isAllowed( 'newuser', 'clustername', 'view' ) );
      $this->assertFalse( $this->object->isAllowed( 'newuser', 'clustername', 'edit' ) );
    }
    
    public function testUserMayBeGrantedEditAccessToPrivateCluster() {
      $this->object->addPrivateCluster( 'clustername' );
      $this->object->addRole( 'newuser', GangliaAcl::GUEST );
      $this->object->allow( 'newuser', 'clustername', array( 'view', 'edit' ) );
      
      $this->assertTrue( $this->object->isAllowed( 'newuser', 'clustername', 'view' ) );
      $this->assertTrue( $this->object->isAllowed( 'newuser', 'clustername', 'edit' ) );
    }
    
}
?>
