language: php
sudo: false
php:
 - '5.1'
 - '5.3'
 - '5.4'
 - '5.5'
 - '5.6'
 - '7.0'
 - nightly
before_script:
 - phpenv rehash
 - export PATH=$PATH:`composer config bin-dir --absolute`
install:
 - composer self-update
 - composer require squizlabs/php_codesniffer
 - composer install
script:
 - make sniff || echo "Completed - Returned $?"
 - make test
