language: php
sudo: false
php:
 - '5.5'
 - '5.6'
 - '7.0'
 - nightly
before_script:
 - pyrus install pear/PHP_CodeSniffer
 - phpenv rehash
script:
 - phpcs --standard=test/phpcs-ganglia-web.xml -p *.php api graph.d lib nagios test || echo "Completed - Returned $?"
 - phpunit test
